---
title: "每週環境"
author: "劉信傑"
date: "9/20/2019"
output: html_document
---

## 環境設置

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
Sys.setlocale("LC_ALL","Chinese")  #解決中文亂碼問題


library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

##mutate、summerise、distinct、unique

```{r}



StuList <- list(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )
StuList 
as.data.frame(StuList) -> StuDFfromList
StuDFfromList
StuDFfromList

StuDF <- data.frame(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )



summarise(StuDF,
          平均成績=mean(成績),
          最高分=max(成績),
          最低分=min(成績),
          )

mutate(StuDF,
      平均成績=mean(成績),
      最高分=max(成績),
      最低分=min(成績),
      
      調分後成績=成績+(最高分-最低分)/5,
          )  ->  StuDF

StuDF

distinct(StuDF,性別)

unique(StuDF$成績)
StuDF

collegeData
unique(collegeData$等級別)

```

```{r}

StuDF <- data.frame(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )
StuDF
mutate(StuDF,
      平均成績=mean(成績),
      調分後成績=成績+(max(成績)-min(成績))/5,
          )  ->  StuDF
StuDF
```



```{r}
library(readr)
collegeData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/103_student.csv")

collegeData


mutate(collegeData,男生=一年級男生+二年級男生+三年級男生+四年級男生)
->collegeData

collegeData$女生<-collegeData$一年級女生+collegeData$二年級女生+collegeData$三年級女生+collegeData$四年級女生
collegeData

mutate(collegeData,男女生比=男生/女生)->collegeData

collegeData
         
View(collegeData
     )
```




```{r}
StuDF
mutate(StuDF,調分後成績=成績+10)->StuDF   #記得回存
mutate(StuDF,調分後成績=成績+10)     
#從data frame 的角度增加欄位(dplyr下)
StuDF$調分後成績 <-  StuDF$成績+10      
#$ : 從list的角度多加一個元素叫做調分後成績
```



```{r}
StuDF <- data.frame(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )
StuDF
mutate(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績)) -> StuDF2

StuDF2
```

## logic、select

```{r}

StuDF2[1]   #column
StuDF2[1,]  #row



StuDF2
mutate(StuDF2,
      調分後成績=成績+(max(成績)-min(成績))/5,) ->StuDF2
StuDF2

names(StuDF2) # 顯示物件內元素名稱
select(StuDF2,
       姓名,學號,成績,調分後成績)
select(StuDF2,
       -次序,-性別,-最高分,-最低分,-平均成績)





StuDF
mutate(StuDF,
      平均成績=mean(成績),
      調分後成績=成績+(max(成績)-min(成績))/5,
          )  ->  StuDF



# logical vector
logiChoose <- c(
  F,F,F,T,T,F,T,F   
  )

StuDF[logiChoose,]    # 使用logical vector選擇所要觀測值"女"




StuDF$性別=="女"     #logical predicate

logiChoose <- StuDF$性別=="女"   #logichoose是一個判斷的向量
StuDF
logiChoose

StuDF[logiChoose,]        #logichoose為TURE是457,所以顯示出457的ROW
StuDF[logiChoose]         #logichoose為TURE是457,所以顯示出457的COLUMN


logiChoose
which(logiChoose)     # which:顯示出哪些row是TURE

slice(  StuDF,
        which(logiChoose)
)                        #slice函數本身選取ROW



moukong <-  collegeData$學校名稱=="國立政治大學"
slice(collegeData,
      which(moukong)
      )
slice(collegeData,
      which(collegeData$學校名稱=="國立政治大學")
)




slice(  StuDF,
        which(StuDF2$性別=="女")
)  


collegeData




slice(collegeData,
      which(collegeData$學校名稱=="國立政治大學")
      )

#方法一
collegeData[collegeData$學校名稱=="國立政治大學",]


#方法二
slice(collegeData,
      which(collegeData$學校名稱=="國立政治大學")
      )



```
##relation operator

```{r}
  #    %in%:屬於
  #     %% :  取餘數
  #   | : or

x4 <- c(1,5,8)
y4 <- c(1,8)

y4 %in% x4


twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime2 <-  ymd_hms("2019-02-01 14:05:00",tz="Asia/Taipei")
class(twDateTime-twDateTime2)
class(twDateTime)
```





```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
class(a+bL)
class(aL+bL)
a+bL
aL+bL

c=2
d=3
d%%c
```

## filter : 篩選

```{r}


StuDF
filter(StuDF,
       性別=="女")
filter(StuDF,
       (性別=="女" & 成績>60))
filter(StuDF,
       性別=="女",
       成績>60) # 多個AND條件可用,分隔



```

##group_by、ungroup、sum

```{r}
StuList <- list(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )


StuDF
group_by(StuDF,性別) -> StuDFG
StuDFG

summarise(StuDFG,最高分=max(成績),平均成績=mean(成績)) -> StuDFGMax
 class(StuDFGMax)

 summarise(StuDF,n())
 summarise(StuDF,sum(成績))
 
 
 
 ungroup(StuDFGMax)-> StuDFGMax
StuDFGMax 
class(StuDFGMax)

```








#exercise
```{r}

collegeData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/103_student.csv")

collegeData


#M1 
filter(collegeData,縣市名稱=="30 臺北市")
filter(collegeData,縣市名稱=="30 臺北市"|縣市名稱=="01 新北市")
#M2
filter(collegeData,縣市名稱 %in% c("30 臺北市"))
filter(collegeData,縣市名稱 %in% c("01 新北市","30 臺北市"))



# 加總一年級男生、女生總數，學校數目
View(collegeData)
str(collegeData)
mutate(collegeData,人數=n()) -> collegeData

summarise(collegeData,
          一年級男生總數=sum(一年級男生),
          一年級女生總數=sum(一年級女生),
          學校數目=NROW(unique(學校名稱))
          )





#全年級男生總數




```






