---
title: "每週環境"
author: "劉信傑"
date: "9/20/2019"
output: html_document
---


##環境設置
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
Sys.setlocale("LC_ALL","Chinese")  #解決中文亂碼問題


library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)

```



## group_by、%>%
```{r}

collegeData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/103_student.csv")

StuDF <- data.frame(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )

#M1
group_by(StuDF,性別)-> StuDF_性別
mutate(StuDF_性別,
       調分後成績=成績+(max(成績)-min(成績))/5
       )->StuDF_依照性別調分

ungroup(StuDF_依照性別調分)-> StuDF_調分後1

StuDF_調分後1

group_by(StuDF,
         性別) -> StuDF_by性別

#M2
StuDF             %>% 
group_by(性別)    %>% 
mutate(調分後成績=成績+(max(成績)-min(成績))/5)    %>%
ungroup()     ->   StuDF_調分後成績2

StuDF_調分後成績2

```


##exercise
```{r}

collegeData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/103_student.csv")




#example
#1將collegeData，依等級別,縣市名稱分群後,

#計算一年級男/女生比例後,

#找出男女生比例最高的等級別,縣市名稱組合。


#M1
collegeData %>% 
  group_by(等級別,縣市名稱)  %>%
  summarise(一年級男女比例=sum(一年級男生)/sum(一年級女生)) %>%
  ungroup()->
  CD

CD[which.max(CD$一年級男女比例),] 
 

#M2
collegeData %>%
  group_by(等級別,縣市名稱) %>%
  summarise(一年級男女生比例=sum(一年級男生)/sum(一年級女生))  %>%
  ungroup() ->
  collegeData_result

which.max(collegeData_result$一年級男女生比例) -> locMax 
collegeData_result[locMax,] %>% View
collegeData_result[which.max(collegeData_result$一年級男女生比例),]%>%View




#example 3
c('學號','學屆','學系','學年','學期','學期成績','學分數','必選修類別（必∕選∕通）') -> names(transcriptDataFinal)

load(url("https://www.dropbox.com/s/duh5aaqgl2f5m3z/loopTranscriptData.Rda?raw=1"))

transcriptDataFinal %>%View
NROW(unique(transcriptDataFinal$學號))    #學生個數
NROW(unique(transcriptDataFinal$學年))  
NROW(unique(transcriptDataFinal$學期))  


transcriptDataFinal %>%
  group_by(學號,學年,學期) %>%
  summarise(學期平均成績=sum(學期成績*學分數)/sum(學分數))  

#ex 計算每位學生每學期學分數在必/選/通 三類的學分數比重。




transcriptDataFinal %>%
  group_by(學號,學年,學期) -> TD

TD   %>%
  summarise(
    AAS=學年+學期
)%>%View



  summarise(TD,
  s=NROW(TD$`必選修類別（必∕選∕通）`) ,
  a=NROW(which(TD$`必選修類別（必∕選∕通）`)=="必"),
  b=NROW(which(TD$`必選修類別（必∕選∕通）`=="選"),
  c=NROW(which(TD$`必選修類別（必∕選∕通）`)=="通"),
  必修比重=a/s,
  選修比重=b/s,
  通識比重=c/s,) %>% 
    ungroup() %>%   View


NROW(which(transcriptDataFinal$`必選修類別（必∕選∕通）`=="必") )


#ex 學屆為100（即100學年入學）的學生，各系學生在學所修總學分數之中位數，何系最高？



```








  








