---
title: "每週一圖作業"
output: html_document
params:
  組員: ["小明","小花"]  
  學號: ["410773818","410773293"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
Sys.setlocale("LC_ALL","Chinese")  #解決中文亂碼問題


library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext);library(ggthemes)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

#### 資料處理

此部份在做：

  * 原始Rda資料引入（即引入**dataList**物件）；
  
  * 資料清理成作圖用graphData物件。

請將你最原始的資料連同作業一起上傳到作業上傳網址：  
  * 若「原始資料為網頁下載」，且下載指令寫在data cleaning chunk裡的話，可以不用上傳「資料」。  
  * 若原始資料有很多個檔案，請先引入成data frame並存在「一個」.Rda檔裡上傳（如`example_data.Rda`檔）。  

資料檔引入到進入作圖前的資料處理請寫在下面區塊，分二部份：

  * 資料處理  
  * 作圖用資料物件生成
  
```{r data cleaning, echo=TRUE, eval=T}
Sys.setlocale("LC_ALL","Chinese")  #解決中文顯示亂碼問題

library(readr)
blood <- read_csv("http://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=385AA125-807A-4C5F-89CE-54B021EDE967", 
    locale = locale(encoding = "BIG5"))

blood %>% mutate(
  單位=factor(單位)
)-> blood
blood %>% gather(
  `250CC捐血袋數量`,`500CC捐血袋數量`,
  key="捐血袋種類",value="袋"
)-> graphData

graphData %>% View()

graphData %>%  
  ggplot(aes(x=捐血人數,y=袋,color="捐血袋種類")+
  geom_line()+
  theme_grey()+
  ggtitle(label =" 替代役役男基礎訓練期間捐血統計表)




```

#### 繪圖程式

```{r graph, echo=T, eval=T}

moneyG %>% 
  ggplot()+ 
  geom_line(aes(x=`年`,y=`貨幣供給/百萬`,color=`貨幣種類/百萬`),size=1,alpha=0.8)+
  geom_point(aes(x=`年`,y=`貨幣供給/百萬`,color=`貨幣種類/百萬`))+
  theme_grey()+
  ggtitle(label = "貨幣流動性高低關係") ->graphData
graphData
graphData %>%　ggplotly()
```

#### 設計說明
說明想傳達的訊息（必要）及設計想法（非必要）。寫在***之後
*** 


