---
title: "每週環境"
author: "劉信傑"
date: "9/20/2019"
output: html_document
---

##環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
Sys.setlocale("LC_ALL","Chinese")  #解決中文亂碼問題


library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext);library(magrittr);library(ggpubr);library(ggrepel)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)


```

## 同學作品
```{r}
library(ggalluvial)
#is_alluvia_form(as.data.frame(graphdata), axes = 1:3, silent = TRUE)
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework3/graphData_homework3_005.Rda?raw=true"))

finalplot<-ggplot(as.data.frame(graphdata),
       aes(y = n, axis1 = age, axis2 =area)) +
  geom_alluvium(aes(fill=性別), width = 1/10) +
  geom_stratum(width = 1/18, fill = "gray", co1lor = "white") +
  geom_label(stat = "stratum", label.strata = TRUE) +scale_x_discrete(limits = c("age", "area"), expand = c(.1, .1)) +scale_fill_brewer(type = "qual", palette = "Set2")+
ggtitle("2018年登革熱病例統計")+ylab('確診人數')+theme(title = element_text(family ="QYuan" ))
finalplot                                                                                           

```


##同學作品 map
```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework3/graphData_homework3_006.Rda?raw=true"))
c('COUNTYNAME','總計家數','總計資本額','農林漁牧業家數','農林漁牧業資本額','礦業及土石採取業家數','礦業及土石採取業資本額','製造業家數','製造業資本額','電力及燃氣供應業家數','電力及燃氣供應業資本額','用水供應及污染整治業家數','用水供應及污染整治業資本額','營造業家數','營造業資本額','批發及零售業家數','批發及零售業資本額','運輸及倉儲業家數','運輸及倉儲業資本額','住宿及餐飲業家數','住宿及餐飲業資本額','資訊及通訊傳播業家數','資訊及通訊傳播業資本額','金融及保險業家數','金融及保險業資本額','不動產業家數','不動產業資本額','專業科學及技術服務業家數','專業科學及技術服務業資本額','支援服務業家數','支援服務業資本額','公共行政及國防；強制性社會安全家數','公共行政及國防；強制性社會安全資本額','教育服務業家數','教育服務業資本額','醫療保健及社會工作服務業家數','醫療保健及社會工作服務業資本額','藝術娛樂及休閒服務業家數','藝術娛樂及休閒服務業資本額','其他服務業家數','其他服務業資本額','未分類家數','未分類資本額','geometry')->names(graphData[[1]])
library(ggrepel)
finalplot <- graphData$my.taiwan.map.data %>% 
ggplot() + geom_sf(aes(fill = 總計資本額/10000)) + scale_fill_distiller(palette = "Spectral",name = "總計資本額(百億元)") + coord_sf(xlim=c(117,123), ylim = c(21,27)) + labs(title="台灣縣市已登記公司總實收資本額分布圖", x ="經度", y = "緯度") + ggrepel::geom_label_repel(
  data = graphData$my.taiwan.map.data[c(10), ],
  aes(label = COUNTYNAME, geometry = geometry),
  stat = "sf_coordinates",
  min.segment.length = 0,
  colour = "white",
  segment.colour = "black",
  arrow = arrow(length = unit(0.03,"npc"),ends = "first"),
  xlim=120, ylim = 25.5,
  fill = "darkorchid2",
  fontface="bold"
) + annotate("text",x = 120, y = 21, 
           label = paste("資料來源：https://data.gov.tw/dataset/8296"), size = 3)
finalplot
```


## 上課資料

```{r}

library2014 <- read_csv("https://www.dropbox.com/s/999hy0u1y98y6ep/library2014.csv?dl=1")
library(readr)
library100_102 <- read_csv("https://www.dropbox.com/s/wuo5o6l55lk68l6/library100_102.csv?dl=1")

library100_102 %>%
  mutate(
    借閱日期=date(ymd_hms(借閱時間)),
    借閱年=year(借閱日期)
  ) -> library100_102

library100_102 %>%
  filter(
    借閱日期 %>% between(ymd("2014-09-01"),ymd("2015-06-30"))
  ) -> library2014  

library2014 %>%
  group_by(學號) %>%
  summarise(
    學院=last(學院),
    讀者年級=max(讀者年級)
  ) %>%
  ungroup() %>%
  mutate(
    讀者年級=讀者年級
    )-> library2014 
library2014 %>%
  mutate(
    學院=reorder(學院,學號,length,order=T),
    讀者年級=reorder(讀者年級,讀者年級, order=T)
  ) -> library2014


graphList<-list()
library2014 %>% 
  ggplot()-> graphList$圖書_ggplotOnly

graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院), fill="#5A99B3", width=0.7
    )
```


##class

```{r}
graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院), 
    geom="bar" # geom_bar內訂會取 count來當y
  )


graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院,y=stat(prop)), 
    geom="bar"                               # geom_bar內訂會取 count來當y
  )


```

##class
```{r}

#M1
graphList$圖書_ggplotOnly +
  stat_count(
    aes(
      x=學院,y=stat(prop),
      group="全校"
      ),
    geom="bar"                               # geom_bar內訂會取 count來當y
  )

#M2

graphList$圖書_ggplotOnly +
  geom_bar(
    aes(
      x=學院,y=stat(prop),
      group="全校"
      ),
    stat = "count"
    # geom_bar內訂會取 count來當y
  )

```

#overide
```{r}

graphList$圖書_ggplotOnly +
  geom_bar(
    aes(
      x=學院,y=stat(prop),
      group="全校"
      ),
    stat = "count"                             # geom_bar內訂會取 count來當y
  )+ stat_count(
    aes(x=學院,y=stat(prop),group="全校",label=round(stat(prop),2)),
    geom="text"
  )

###

graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院,y=stat(prop)),
    stat="count"
  )+
  geom_text(
    aes(x=學院,y=stat(prop),group="全校",label=round(stat(prop)),2),
    stat = "count",
    nudge_x =+0.2 ,
    nudge_y = +0.1
  )

####   class
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院, y=stat(prop), group="全校") 
  )+
  geom_text(
    aes(
      x=學院,
      y=stat(prop), group="全校",
      label=round(stat(prop),digits=2)),
    stat="count",
    color="white",nudge_y=-0.01
  )+
  labs(
    title="各院借閱人次佔總人次比",x="",y=""
  )





```



## stat manually
```{r}

df_x <- data.frame(
  x=rnorm(500,mean=2,sd=1)
)
```

## stat manually
```{r}
df_x %>%
  ggplot(aes(x=x))+
  geom_histogram(
    aes(y=stat(desity)),bins = 50
  )+
  stat_function(
    fun=dnorm, args = list(mean=2, sd=1) # dnorm 為常態分配density函數
  )

df_x %>%
  ggplot(aes(x=x))+
  geom_histogram(
    aes(y=stat(count)),bins = 50
  )+
  stat_function(
    fun=dnorm, args = list(mean=2, sd=1) # dnorm 為常態分配density函數
  )


```


##    maunel funtion
  
```{r}
market_demand <- function(x, a=1, b=-1){
  return(a+b*x)
}

market_supply <- function(x, a=0, b=1){
  return(a+b*x)
}
```


```{r}
df_grids <- 
  data.frame(
    x=seq(0,1,by=0.2))            # 定義 x 範圍

df_grids %>%
  ggplot(aes(x=x))+
  stat_function(
    fun="market_demand"
  )+
  stat_function(
    fun="market_supply"
  )+
  scale_y_continuous(
    limits = c(0,1)
  )+
  labs(
    x="Quantity", y="Price"
  ) -> graphList$demand_supply


graphList$demand_supply+
  stat_function(
    fun="market_demand",
    args=list(b=-2), color='red'
  )

graphList$demand_supply
```
## surpluse
```{r}

graphList$demand_supply+

    geom_ribbon(
    data=data.frame(
      x=seq(0.25,0.5,by=0.01)
    ),
    aes(y=x),
    stat="summary", 
    fun.ymin= function(y) market_demand(y),
    fun.ymax= function(y) market_supply(y),
    alpha=0.3
  )



```







