---
title: "每週環境"
author: "劉信傑"
date: "9/20/2019"
output: html_document
---

##環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
Sys.setlocale("LC_ALL","Chinese")  #解決中文亂碼問題


library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext);library(magrittr)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)


```

##  stat
```{r}
d <-  ggplot(mtcars, aes(cyl, mpg)) + geom_point()
  
  
  
  
d %>% ggplot(mtcars, aes(cyl, mpg)) + geom_point(inherit.aes = T)+stat_summary(fun.y = "median", colour = "red", size = 2, geom = "point",inherit.aes = T)


ggplot(mtcars, aes(factor(cyl), fill = factor(vs))) +
  geom_bar(position = position_dodge2(preserve = "single"))
```


##path and line

```{r}
df0 <- data.frame(
  x=c(1,2,1,3,2),
  y=c(2,3,1,2,4),
  label=c("a","b","c","d","e")
)
df0 %>%
  ggplot(aes(x=x,y=y))+
  geom_label(
    aes(label=label), fill="pink"
    )-> plotbase0

list_graphs <- list()

plotbase0+geom_line()+labs(title="geom_line") -> 
  list_graphs$geom_line

plotbase0+geom_path()+labs(title="geom_path") -> 
  list_graphs$geom_path

ggpubr::ggarrange(
  list_graphs$geom_line, list_graphs$geom_path
)
```



## grid
```{r}
ggplot()+theme_linedraw()+
  scale_x_continuous(limits=c(0,6),breaks=0:6,
  expand=expand_scale(add=c(0,0)))+         ###### 讓圖形從原點開始
  scale_y_continuous(limits=c(0,6),breaks=0:6,
  expand=expand_scale(mult = c(0,0))) ->
  myGrids

myGrids
```

## demonstrate
```{r}
list_geometryData <- list()
list_geometryData$points <- 
  rbind(
    c(1,5),
    c(2,1),
    c(5,1),
    c(5,5)) 

list_geometryData$points %>%
  as.data.frame() 


#
myGrids +
  geom_point(
    data=as.data.frame(list_geometryData$points),
    aes(x=V1,y=V2)
  ) -> list_graphs$point

#
myGrids +
  geom_path(
    data=as.data.frame(list_geometryData$points),
    aes(x=V1,y=V2)
  ) -> list_graphs$path

#
myGrids +
  geom_polygon(
    data=as.data.frame(list_geometryData$points),
    aes(x=V1,y=V2)
  ) -> list_graphs$polygon
list_graphs$polygon

#
ggpubr::ggarrange(
  list_graphs$point, list_graphs$path, list_graphs$polygon,
  ncol=3
)
```


## class
```{r}
#library(readr)
df_geo_northTW <- read_csv("https://www.dropbox.com/s/6uljw24zkyj7avs/df_geo_northTW.csv?dl=1")
#df_geo_northTW %>% view()
filter(df_geo_northTW,COUNTYNAME=="新北市")  ->data0
 
data0  %>% 
  ggplot()+
  geom_path(
  aes(x=x,y=y)
)

data0  %>% 
  ggplot()+
  geom_polygon(
  aes(x=x,y=y)
)+theme_linedraw()


```


## make a hole
```{r}
list_geometryData$hole <-
  rbind(
    c(2,4),
    c(3,2),
    c(4,3)
  )                               ###the hole cordination

###

list_geometryData$points %>%
  as.data.frame() -> df_part1
list_geometryData$hole %>%
  as.data.frame() -> df_part2

df_part1 %>%
  mutate(
    sub_id=1
  ) -> df_part1
df_part1
df_part2 %>%
  mutate(
    sub_id=2
  ) -> df_part2
df_part2
bind_rows(
  df_part1,
  df_part2
) -> df_all

df_all %>%
  mutate(
    group_id="A"
  ) -> df_all

#########################
myGrids +
  geom_polygon(
    data=df_all,
    aes(x=V1,y=V2, group=group_id, subgroup=sub_id)             ##################
  )
```



##solve map hole
```{r}
filter(df_geo_northTW,COUNTYNAME=="新北市")                         ->dataNewNorth
filter(df_geo_northTW,COUNTYNAME=="臺北市"|COUNTYNAME=="新北市")    ->dataTaipei

dataTaipei %>% mutate(
  group_id="新北市"
)  ->dataTaipei 

```
```{r}
df_geo_northTW %>%
  ggplot()+
  geom_polygon(
    aes(x=x,y=y,fill=COUNTYNAME), color="azure4"
  ) -> list_graphs$northTW
list_graphs$northTW
# load(url("https://www.dropbox.com/s/9n7b1bcs09gnw0r/ggplot_newTaipei.Rda?dl=1")) # 前個練習若沒做出來，執行此行

list_graphs$northTW +
#  theme_linedraw()+
  geom_path(
    data=data.frame(
      x=c(121.55,121.7,121.9),
      y=c(25.1,24.7,24.7)
      ),
    aes(x=x,y=y)
    )+
  annotate(
    "text",
    x=121.9,y=24.71,label="這是臺北市",
    vjust=0
  )+
  theme_void()


```

## 套入圖片
```{r}
library(magick)

image_read("https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/2450df20386177.562ea7d13f396.jpg") -> taipei101

taipei101 %>%
  image_info() -> taipei101info
taipei101info

ggplot()+theme_linedraw()+
  theme(
    panel.background = element_rect(fill="cyan4")
  )

theme_linedraw()+
  theme(
    panel.background = element_rect(fill="cyan4")
  ) -> A

# 圖片底色非透明
taipei101 %>%
  image_ggplot()+A






image_fill(taipei101, "transparent", point = "+100+100", fuzz = 20) %>% # fuzz=對邊界定義模糊度 %>%
    image_ggplot()+A






```








