---
title: "每週環境"
author: "劉信傑"
date: "9/20/2019"
output: html_document
---

##環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
Sys.setlocale("LC_ALL","Chinese")  #解決中文亂碼問題


library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext);library(magrittr);library(sf);

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)


```

#作業    同學作品
```{r}
#找一張履歷   視覺化他的履歷    讓人知道它的優點


#1  查看原始碼 
#   ggthemes:::theme_economist

#2
#  Y軸轉正 文字與軸線距離等細部調整
#  theme(axis.title.x = element_blank(),
#        axis.title.y = element_text(angle = 0,
#                                    margin = margin(r = -10)),
#        axis.title.y.right = element_text(angle = 0, vjust = 1,
#                                          margin = margin(l = -10))
#        )

```

#sf
```{r}
outer <-     
  rbind( # 外圍
    c(1,5),
    c(2,1),
    c(5,1),
    c(5,5),
    c(1,5)) # 必需自行輸入起點close it

hole <-
  rbind( # 洞
    c(2,4),
    c(3,2),
    c(4,3),
    c(2,4))  # 必需自行輸入起點close it

outer2 <- outer + 12
hole2 <- hole + 12


sfg_county1 <- st_polygon(list(
  outer,hole
))
sfg_county2 <- st_polygon(list(
  outer2, hole2
))

sfc_county12column <- st_sfc(sfg_county1,sfg_county2)



sfc_county12column %>%
  st_set_crs(4326) -> # EPSG: 4326
  sfc_county12column



# st_set_geometry(df,geo_column)
df_county12 <- data.frame(
  name=c("county1","county2"),
  population=c(100,107)
)

df_county12 %>%
  st_set_geometry(sfc_county12column) -> df_county12

df_county12 %>% names

dir.create("county12")
write_sf(df_county12,"county12/county12.shp")


load(url("https://www.dropbox.com/s/uvco1te2kbs6o01/MRT_Taipei.Rda?dl=1"))
sf_county12=read_sf("county12/county12.shp")

sf_mrt_tpe %>% 
  filter(
    str_detect(經過路線,"BL")
  )  -> sf_mrt_tpe_bl

sf_mrt_tpe_bl  %>% st_coordinates()          #這已經是矩陣
  
st_linestring()  -> sfg_mrt_bl
sfg_mrt_bl %>% ggplot()+geom_sf()
```

```{r}
sf_mrt_tpe_bl %>% 
  mutate(
    站號=stringr::strextract(
      經過路線,""
    )
  )

#unique(sf_mrt_tpe$MARKNAME1)

<-  read_sf("C://Users/Leo jay//Desktop//mapdata201907311006//COUNTY_MOI_1080726.shp")


data(world,package="spData")
class(world) # 已是sf object
world %>% st_geometry() %>%
  ggplot()+geom_sf()
```


#  10/30
```{r}
 load(url("https://www.dropbox.com/s/9n7b1bcs09gnw0r/ggplot_newTaipei.Rda?dl=1")) # 前個練習若沒做出來，執行此行
library(readr)
df_geo_northTW <- read_csv("https://www.dropbox.com/s/6uljw24zkyj7avs/df_geo_northTW.csv?dl=1")
list_graphs <- list()


df_geo_northTW %>%
  ggplot()+
  geom_polygon(
    aes(x=x,y=y,fill=COUNTYNAME), color="azure4"
  ) -> list_graphs$northTW
list_graphs$northTW

df_geo_northTW %>%
  ggplot()+
  geom_polygon(
    aes(x=x,y=y,fill=COUNTYNAME), color="azure4"
  ) -> list_graphs$northTW
list_graphs$northTW


list_graphs$northTW +
  theme_linedraw()+
  geom_path(
    data=data.frame(
      x=c(121.55,121.7,121.9),
      y=c(25.1,24.7,24.7)
      ),
    aes(x=x,y=y)
    )+
  annotate(
    "text",
    x=121.9,y=24.71,label="這是臺北市",
    vjust=0
  )+
  theme_void()

```



```{r}

theme(
  panel.background = element_rect(fill="red")
)



```
















