---
title: "每週環境"
author: "劉信傑"
date: "9/20/2019"
output: html_document
---

##環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
Sys.setlocale("LC_ALL","Chinese")  #解決中文亂碼問題


library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext);library(magrittr)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)


```

#osmdata
```{r}
download.file("https://www.dropbox.com/s/wisgdb03j01js1r/map.osm?dl=1",
              destfile = "map.osm")
st_layers("map.osm")

st_layers("map.osm") ->  layers_map 
layers_map %>% View
layers_map

```


#
```{r}
st_read("map.osm",layer="lines") -> sf_ntpu_lines

sf_ntpu_lines %>%  ggplot+geom_sf()

sf_ntpu_lines %>% filter(
  !is.na(name)
) %>% ggplot+geom_sf()

st_read("map.osm",layer="points")->sf_ntpu_points

sf_ntpu_points %>% ggplot+geom_sf()

```


# sf_ntpu_polygons
```{r}
st_read("map.osm",
        layer="multipolygons"
        )  ->sf_ntpu_polygons

sf_ntpu_polygons %>% ggplot()+geom_sf() ->gg_ntpu

########
gg_ntpu+geom_sf(
  data=sf_ntpu_lines
)+
  geom_sf(
    data=sf_ntpu_points,
    aes(color=highway,fill=highway)
  )+coord_sf(
    xlim=c(121.357,121.38),
    ylim=c(24.936,24.949)
  )


```

# save   存檔  可存成jpg,png,svg  等檔     或按圖按右鍵另存
```{r}
 gg_ntpu %>% ggsave(filename="gg_ntpu.jpg")
```

#osm bbox
```{r}
#Overpass query  :opq


```

#Guides
```{r}

```

# facet
```{r}



load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework6/graphData_homework6_021.Rda?raw=true"))
source("https://www.dropbox.com/s/0ydtqtxu5guy6i1/theme_lin.R?dl=1")

resume_df %>% 
  mutate(開始 = ymd(開始), 結束 = ymd(結束))  -> resume_df

resume_df %>%
  ggplot(
    aes(x = 開始, y = 項目)) +    
  geom_text(
    aes(label = 名稱), size = 2.5) + 
  geom_segment(
    aes(
      xend = 結束, yend = 項目, color = 分類, size = 2, alpha = 1
      )
    ) +
  scale_x_date(
      breaks = seq(as.Date("2015-01-01"), as.Date("2020-01-01"), by="1 year"),
      labels = scales::date_format("%Y")
      )+
  labs(title = "Kuo, Shih-Jung  郭士榮", subtitle = "熱愛挑戰不設限、豐富國際經驗、在學三份實習") + 
  theme_lin() -> gg_basic

gg_basic
```


# facet_rid
```{r}
# facet  ~為簡易寫法

gg_basic +
  facet_grid(.~分類) -> gg_facet_column

gg_basic +
  facet_grid(分類~.) -> gg_facet_row


gg_facet_column
gg_facet_row


# ~改成正是寫法  row跟col
gg_basic +
  facet_grid(
    rows=vars(分類)
    ) -> gg_facet


gg_basic +
  facet_grid(
    cols=vars(分類)
    ) -> gg_facet2


gg_facet
gg_facet2

```


# 讓y軸 變乾淨
```{r}
gg_basic +
  facet_grid(分類~.,  scales = "free_y") -> gg_facet_free

gg_facet_free
```


# free space and free scale
```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework3/graphData_homework3_002.Rda?raw=true"))

graphData$sub_2015_city%>%
  arrange(desc(area), avg_nh)%>%
  mutate(city = forcats::fct_inorder(city)) -> df_eldercare

df_eldercare %>%
  ggplot(
    aes(y = avg_nh, x = city, fill = area)
    )+
  geom_col(
    width=0.7
  )+
  coord_flip()+
  labs(x = "長照機構數(每10,000位老人)", y="")+
  theme_lin() -> gg_original

gg_original

gg_original+
  facet_grid(
    rows=vars(area), scales="free_y"
  )

#多free space
gg_original+
  facet_grid(
    rows=vars(area), scales="free_y", space="free_y"
  )
```




