---
title: "範本"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    css: ['css/mystyle.css']
    includes:
      in_header: ["external/in_header/header.html"]
      before_body: ["external/before_body/bf_body.html"]
      after_body: ["external/after_body/af_body.html"]
---

```{r setup, include=FALSE}
library(flexdashboard)

```

控制台 {.sidebar}
------------------------
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a>
  </div>
</div>
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

